feat: move room initialization code into manager
godot-escoria/escoria-demo-game pull request #479
Opened 2021-12-07 17:02 UTC by BHSDuncan

2021-12-07 18:07 UTC, dploeger requested changes
This looks very good already. Can you add the relevant part of the change_scene command as well?

2021-12-07 18:07 UTC, dploeger commented on addons/escoria-core/game/core-scripts/esc/esc_room_manager.gd
> +# name of this node if it's not set manually
Please document the parameter as well here

2021-12-09 08:36 UTC, dploeger requested changes
Some smaller remarks about things that already were in the code. It makes sense to fix them here.

2021-12-09 08:36 UTC, dploeger commented on addons/escoria-core/game/core-scripts/esc/esc_room_manager.gd
> +# * room_path: Node path to the room that is to become the new current room.
Please use dashes instead of asterisks. I think, we're using dashes everywhere else.

2021-12-09 08:36 UTC, dploeger commented on addons/escoria-core/game/core-scripts/esc/esc_room_manager.gd
> +			and (
I'd put that in the line above so that all the following lines can be indented more to the left.

2021-12-09 08:36 UTC, dploeger commented on addons/escoria-core/game/core-scripts/esc/esc_room_manager.gd
> +	# Load game scene
It's more "check if game scene was loaded"

2021-12-13 06:33 UTC, StraToN approved these changes

2021-12-13 06:35 UTC, StraToN commented
Perfect! Thanks a lot!

2021-12-13 06:35 UTC, merged

2021-12-13 08:04 UTC, StraToN commented
Fixes https://github.com/godot-escoria/escoria-issues/issues/88