feat: Updated room 2 and 3 graphics
godot-escoria/escoria-demo-game pull request #492
Opened 2022-02-13 11:53 UTC by balloonpopper

feat: Updated room 1 graphics. Merged child scenes into master scene for clarity.
Previously shared bridge resource moved to level3 folder, and button resource moved to level9 folder.

2022-02-13 20:48 UTC, StraToN commented
I have tested your branch. It looks awesome! However your change broke room03 (probably because room03 references the bridge from room02), so the game crashes when you leave room02 to room03.

2022-02-14 13:26 UTC, dploeger requested changes
The animation is really great! Thanks!

@StraToN @BHSDuncan I'm not 100% sure about all the whitespace changes. While we should definitely apply them, my "cleanness" feeling suggests moving them to another PR to not mix things up. I'll let you decide.

2022-02-14 17:13 UTC, dploeger commented
@balloonpopper I guess you didn't make that changes manually, right? Was it some kind of autoformat which caused them? Maybe we can run that autoformatter over the whole sourcecode in another PR.

2022-02-14 23:45 UTC, balloonpopper commented
@dploeger  / @BHSDuncan  - The edits to the gd files are made automatically by Godot when you run the project. I've removed the whitespace in all .gd with sed under another change now - see https://github.com/godot-escoria/escoria-demo-game/pull/494

2022-02-14 23:47 UTC, balloonpopper commented on .gitignore
> +addons/escoria-core/default_bus_layout.tres
Removed. I'll raise it as a bug instead.

2022-02-15 07:40 UTC, dploeger approved these changes

2022-02-15 07:40 UTC, dploeger commented
Wonderful. Thanks a lot! 🎁

2022-02-15 16:54 UTC, StraToN commented on addons/escoria-core/default_bus_layout.tres
> +bus/1/volume_db = -60.0
Yes I always do as well. Not sure what to do with them. I usually commit the change, hoping that it won't be required anymore for others.

2022-02-15 16:56 UTC, StraToN approved these changes

2022-02-15 17:21 UTC, merged

2022-02-15 17:53 UTC, dploeger commented on addons/escoria-core/default_bus_layout.tres
> +bus/1/volume_db = -60.0
Recorded in #107