fix: Make sure escoria#apply_settings is only called in game and not in editor
godot-escoria/escoria-demo-game pull request #543
Opened 2022-03-12 19:50 UTC by dploeger

Found this during the stream and was annoyed. 😉

2022-03-12 21:37 UTC, BHSDuncan approved these changes

2022-03-15 06:08 UTC, balloonpopper commented on addons/escoria-core/game/escoria.gd
> +	if !Engine.is_editor_hint():
```suggestion
	if not Engine.is_editor_hint():
```

2022-03-15 06:09 UTC, balloonpopper requested changes
Added comment to change ! to "not" as per today's stream

2022-03-15 06:43 UTC, StraToN approved these changes

2022-03-15 06:45 UTC, merged

2022-03-15 06:45 UTC, StraToN commented
Thanks!

2022-03-15 08:21 UTC, dploeger commented
Oh, wonderful. You already fixed it! Thanks a lot. And I just wondered what I forgot to do after the stream! 😆