feat: Updated exit documentation
godot-escoria/escoria-demo-game pull request #545
Opened 2022-03-18 03:37 UTC by balloonpopper

Clarifying when to use ESCexit instead of ESCitem.

2022-03-18 07:17 UTC, dploeger requested changes
Awesome. Some small remarks.

2022-03-18 07:17 UTC, dploeger commented on addons/escoria-core/game/core-scripts/esc_exit.gd
> +# sound effect.)
```suggestion
# sound effect).
```

2022-03-18 07:17 UTC, dploeger commented on addons/escoria-core/game/core-scripts/esc_item.gd
> +# ESCItem is a Sprite that defines an item, potentially interactive.
Ah, I just see it's actually not a sprite. That suggests a visual representation. You still need to add an actual Sprite2D to it. We should change that bit as well while you're at it.

I'd suggest:
```suggestion
# ESCItem defines a potentially interactive item of the game.
```

2022-03-18 09:47 UTC, balloonpopper commented on addons/escoria-core/game/core-scripts/esc_item.gd
> +# ESCItem is a Sprite that defines an item, potentially interactive.
```suggestion
ESCItem defines a potentially interactive item in the game.
```

2022-03-18 09:48 UTC, balloonpopper commented
Updated @dploeger

2022-03-18 09:50 UTC, balloonpopper commented on addons/escoria-core/game/core-scripts/esc_exit.gd
> +# An item that streamlines exiting scenes.
```suggestion
# An ESCExit is an item that streamlines the process to exit a scene.
```

2022-03-18 12:06 UTC, dploeger approved these changes
Wonderful. Thanks. 🎁

2022-03-18 15:45 UTC, BHSDuncan requested changes

2022-03-18 15:45 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc_exit.gd
> +# a cutscene for example, use an ESCItem with "Is Exit" selected instead.
```suggestion
# If you want to attach the exit to a script to perform additional actions -
# a cutscene for example - use an ``ESCItem`` with "Is Exit" selected instead.
```

2022-03-18 15:45 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc_exit.gd
> +# child of an ESCExit node.
```suggestion
# The game character will automatically walk to an ``ESCLocation`` created as a
# child of an ``ESCExit`` node.
```

2022-03-18 15:45 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc_item.gd
> +# character to the next room.
```suggestion
# An ``ESCItem`` defines a (usually interactive) item in the game.
#
# When interacting with an ``ESCItem``, the game character will automatically
# walk to an ``ESCLocation`` that is created as a child of an ``ESCItem``.
#
# By selecting the "Is Exit" checkbox when you create an ``ESCItem``
# node, Escoria will look for an ``:exit_scene`` event in the attached script file.
# Any commands you place in the ``:exit_scene`` event will be run when the player
# chooses to "use" the exit - for example, saying a goodbye, or running a
# cutscene. Place a ``change_scene`` command inside this event to move the
# character to the next room.
```

2022-03-18 15:45 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc_item.gd
> +# For simple exits that do not require scripted actions, the ESCExit node may be
```suggestion
# If true, the ESC script may have an ``:exit_scene`` event to manage scene changes.
# For simple exits that do not require scripted actions, the ``ESCExit`` node may be
```

2022-03-21 21:25 UTC, StraToN approved these changes

2022-03-21 21:29 UTC, BHSDuncan approved these changes

2022-03-21 21:31 UTC, merged