refactor: remove deprecated debug command
godot-escoria/escoria-demo-game pull request #572
Opened 2022-04-15 02:53 UTC by balloonpopper

- Removed "debug" as it's been replaced by print (which works at all debug levels)
- Fixed issue where print didn't interpolate the globals in the text in all instances
- Updated the debug console to use print over debug. Compared output in the debug window when using print vs debug and the 11 debug output lines are identical (repacing everywhere that says "debug" with "print")
- Deduplicated the replace_globals function

Fixes : https://github.com/godot-escoria/escoria-issues/issues/221

2022-04-16 00:51 UTC, BHSDuncan requested changes

2022-04-16 00:51 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc/commands/print.gd
> +	print(escoria.logger._replace_globals(command_params[0]))
If you're going to use `_replace_globals`, then it'll either need to be renamed to follow a public method convention, or you'll have to make a public method that defers to `_replace_globals` in the same class.

2022-04-16 00:51 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd
>  const EVENT_DEBUG = "debug"
If we're removing `debug` all together, can we remove this constant? Or is it used elsewhere?

2022-04-16 18:09 UTC, BHSDuncan approved these changes

2022-04-17 08:03 UTC, balloonpopper commented
Fixes https://github.com/godot-escoria/escoria-issues/issues/204
Fixes https://github.com/godot-escoria/escoria-issues/issues/221

2022-04-19 06:00 UTC, StraToN approved these changes

2022-04-21 07:54 UTC, merged