Fix: disable ESCGame inputs until signal room_ready is emitted
godot-escoria/escoria-demo-game pull request #582
Opened 2022-04-20 18:08 UTC by StraToN

Fixes a crash happening when game scene was receiving inputs while changing the scene.

2022-04-20 18:25 UTC, BHSDuncan commented
Looks ok, but I'd still want to know what was introduced in Godot 3.4.4 that causes this.

@balloonpopper can you please regression test this against previous versions of Godot?

2022-04-21 08:11 UTC, balloonpopper approved these changes
The issue we were seeing was that moving the mouse in the Godot window while the game was starting would break the game with a tooltip error. This happened only in simplemouse and not in 9-verb.

The updated fix has been tested against 9 verb and simplemouse in 3.4.4, 3.3 and 3.2
Tested with starting a full game and loading directly into a scene.
Moving the mouse as the game starts doesn't break the game under this change.

2022-04-21 08:27 UTC, balloonpopper commented on addons/escoria-core/game/escoria.gd
> +# must be set and game scene must've been notified that room is ready.
```suggestion
# from _input() function. To do so, the current_scene must be set, the game
# scene must be set, and the game scene must've been notified that room
# is ready.
```

2022-04-26 23:50 UTC, BHSDuncan requested changes

2022-04-26 23:50 UTC, BHSDuncan commented on addons/escoria-core/game/escoria.gd
> +# scene must be set, and the game scene must've been notified that room
```suggestion
# from the _input() function. To do so, the current_scene must be set, the game
# scene must be set, and the game scene must've been notified that the room
```

2022-04-30 16:11 UTC, BHSDuncan approved these changes

2022-04-30 18:10 UTC, merged