fix: manage clearing of current_action when action is interrupted
godot-escoria/escoria-demo-game pull request #584
Opened 2022-04-21 22:33 UTC by StraToN

Fixes https://github.com/godot-escoria/escoria-issues/issues/222
Fixes https://github.com/godot-escoria/escoria-issues/issues/117

2022-04-21 22:36 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd
> -	if return_code == ESCExecution.RC_CANCEL:
@dploeger can you maybe tell us why this block was here originally? It seems to just swallow a cancelled execution for some reason.

2022-04-21 22:36 UTC, BHSDuncan commented
@dploeger can you maybe tell us why the block at L284 of the event manager was there originally? It seems to just swallow a cancelled execution for some reason.

2022-04-21 22:37 UTC, BHSDuncan approved these changes

2022-04-22 04:46 UTC, dploeger commented
> @dploeger can you maybe tell us why the block at L284 of the event manager was there originally? It seems to just swallow a cancelled execution for some reason.

I think so. The RC_CANCEL is returned from the stop command, which cancels the current event but not in a failed way. So for the event handling the stop command I returned a successful code. 

At least that was my thinking behind it.

2022-04-22 06:26 UTC, balloonpopper requested changes
From my testing, switching scenes is currently broken with this patch.
Additionally,  the animation sometimes jumps (or the the walk cycle is reset?) when you interrupt the current action which would be good to correct.

2022-04-24 11:23 UTC, balloonpopper commented
I've tried lots of different things to break the issue-222 branch (including room changes, interruptions at different times, bringing in an inventory item and using "pick up" to interrupt it). I've found 2 issues.
1) Wait doesn't get interrupted as mentioned above
2) I brought the "worker" in from a different room and made him walk around. If I interrupt the player, the worker's "walk" command is not interrupted.  This might be a problem, or might be expected behavior as I don't think we've discussed this use-case.

2022-04-25 20:09 UTC, StraToN commented
@balloonpopper

> From my testing, switching scenes is currently broken with this patch.
> Additionally, the animation sometimes jumps (or the the walk cycle is reset?) when you interrupt the current action which would be good to correct.

 I may have fixed the issues with latest commit. Thanks for retesting!

2022-04-26 10:41 UTC, balloonpopper requested changes
Marking this as "Request changes" temporarily until I find out if you want to deal with the below bugs as separate issues.

* The animation still breaks when you interrupt the walking (I think it resets the walking animation frame? Also seems to move Mark a few pixels to the right so the walking isn't smooth)
* As mentioned on https://github.com/godot-escoria/escoria-demo-game/pull/588
(I don't know if you want to look at the issue I mentioned on 588 as part of this fix?) If you interrupt Mark walking by right clicking picture 2, then while he's walking to picture 2, right click picture 1 - Mark will walk to picture 1 and do both picture 1 and 2's talk actions.

* Confirming 117 is now fixed.
* Confirming 248 is now fixed.

2022-04-27 00:08 UTC, BHSDuncan approved these changes
Nothing really jumps out at me as being wrong with the code. And also, I love the Command pattern for the reasons in this PR. :) Looks good! Good work!

2022-04-30 17:59 UTC, StraToN commented
@balloonpopper 

> Marking this as "Request changes" temporarily until I find out if you want to deal with the below bugs as separate issues.
> 
>     * The animation still breaks when you interrupt the walking (I think it resets the walking animation frame? Also seems to move Mark a few pixels to the right so the walking isn't smooth)

I think it's not related to this issue. I advise creating a separate issue for this one.

>     * As mentioned on #588
>       (I don't know if you want to look at the issue I mentioned on 588 as part of this fix?) If you interrupt Mark walking by right clicking picture 2, then while he's walking to picture 2, right click picture 1 - Mark will walk to picture 1 and do both picture 1 and 2's talk actions.

While this looks related to interruptions, that is also a different issue - or at least, it can be managed as a separate issue.

2022-05-01 00:41 UTC, balloonpopper commented
Raised https://github.com/godot-escoria/escoria-issues/issues/259
and
https://github.com/godot-escoria/escoria-issues/issues/258

2022-05-01 00:43 UTC, balloonpopper approved these changes

2022-05-01 10:48 UTC, merged