fix: allows for transitions to be disabled during :init event
godot-escoria/escoria-demo-game pull request #585
Opened 2022-04-24 01:13 UTC by BHSDuncan

Also does the following:

- Eliminates UI flicker during game startup
- Eliminates menu disappearing resulting in flicker of previous scene when transitioning to first scene during `:newgame`

These should be tested against saving and loading games when the system is back in working order.

2022-04-24 01:44 UTC, balloonpopper approved these changes

2022-04-24 01:45 UTC, balloonpopper commented
Tested and it's working as expected for me across both the intro and the first couple of screens.

2022-04-24 12:06 UTC, balloonpopper reviewed
@BHSDuncan - I now get into the intro cutscene and then intothe menu without a transition. 
I can't see a way now though to have a cutscene to the menu if I want one - is there a way?

2022-04-24 16:32 UTC, BHSDuncan commented
> @BHSDuncan - I now get into the intro cutscene and then intothe menu without a transition. I can't see a way now though to have a cutscene to the menu if I want one - is there a way?

I think one of the rooms (14?) demonstrates that you can have a transition before going into a menu. So, yes, I think it's possible. If you can't see a way, let's discuss on Discord when we're able.

Otherwise, I'd think that using a `transition` command before calling `show_menu` would work.

2022-04-25 01:31 UTC, balloonpopper commented
Yep, it's just wrapping the menu call in transitions.
```
transition curtain out
show_menu main
transition curtain in
```
Cheers!

2022-04-25 05:48 UTC, StraToN requested changes

2022-04-25 05:48 UTC, StraToN commented on addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd
> +	  return_code = ESCExecution.RC_OK
1 tab turned into 2 spaces. Please set it back to 1 tab :)

2022-04-25 05:48 UTC, StraToN commented
Thanks for the explanation of the change in esc_transition!

2022-04-30 18:03 UTC, BHSDuncan commented
Fixes #198

2022-04-30 18:05 UTC, StraToN approved these changes

2022-04-30 18:06 UTC, merged