fix: prevents improper events/commands from being queued while changing scenes
godot-escoria/escoria-demo-game pull request #595
Opened 2022-05-07 22:07 UTC by BHSDuncan

Fixes https://github.com/godot-escoria/escoria-issues/issues/249

2022-05-08 14:54 UTC, StraToN requested changes

2022-05-08 14:54 UTC, StraToN commented on addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd
> +func _init():
Missing comment here

2022-05-08 14:54 UTC, StraToN commented on addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd
> +var _change_scene: ChangeSceneCommand
Missing comment here

2022-05-08 14:54 UTC, StraToN commented on addons/escoria-core/game/core-scripts/esc/esc_event_manager.gd
> +	if value:
This changes makes the test clearer:
```suggestion
	if _changing_scene:
```
Also possible to rename the `value` variable for `p_is_changing_scene` instead.

2022-05-08 14:54 UTC, StraToN commented on addons/escoria-core/game/core-scripts/esc/types/esc_base_command.gd
> +	escoria.logger.info("Command %s did not override interrupt." % get_command_name())
This could be a TRACE log, I think.
```suggestion
	escoria.logger.trace("Command %s did not override interrupt." % get_command_name())
```

2022-05-09 11:58 UTC, balloonpopper commented
With the latest PR, clicking while transitioning causes issues. 
1) Start in room 3. Click to room 2. While the transition out is happening, right click somewhere on the right platform. When room 2 transitions in, Mark walks to the mouse position you clicked while in room 3.
2) If you start in room 3, click the 3->2 doorway. As the room change is happening, click door 3->4. He's now stuck. The transition doesn't run and you can't move. "Changing scenes. Won't queue event 'exit_scene'."
You can change the active verb (9verb) but clicking on the button in the room does nothing. Console log : "Changing scenes. Won't queue event 'look'."
3) In room 3, click the 3->4 door then click the 3->2 door while he's walking. Room 4 loads when room 2 is expected.

2022-05-09 11:58 UTC, balloonpopper requested changes
See my comment for the issues I found

2022-05-10 13:28 UTC, balloonpopper commented
Observations from testing this PR.
1) I got this debug output when I interrupted a 3->2 transition. I'm not sure if the current behavior is that you should be able to interrupt change_scenes, but I didn't expect I should be able to.
`ESC 2022-05-10T23:03:03 (I)	Activated action exit_scene on [Node:37641] 	[]
ESC 2022-05-10T23:03:03 (D)	Queueing exit_scene in channel _front. 	
ESC 2022-05-10T23:03:03 (I)	Left click on background at  	[(219, 474)]
ESC 2022-05-10T23:03:03 (D)	Interrupting queued event exit_scene in channel _front... 	
ESC 2022-05-10T23:03:03 (I)	Interrupting event exit_scene ([Object:37654]) 	[]
 ESC 2022-05-10T23:03:03 (W)	Warnings in file change_scene
Interrupt() function not implemented
`
2) I can't force the wrong room to load anymore
3) It pauses before it starts transitioning out, and between transition out and in that it never used to. Particularly with "instant" transitions, the transitions aren't the most "instant" any more. 
To clarify from further testing. I generally play on TRACE (because it's ended up set like that - probably from some previous test - and I just don't think to change it :D ) - under TRACE there's more of a lag then there was (maybe we're logging more now with blocked interruptions?) The response time under "DEBUG" is certainly acceptable - so I won't fault you if you put this in the "will not fix" category.
4) Loading directly into room 1 (play scene) - if I click on the right hand side of the screen (walkable area) while curtain transition-in is running, it crashes.
![image](https://user-images.githubusercontent.com/5151242/167636207-0d7b24ed-3961-4a2d-86cf-36f61e083028.png)

![image](https://user-images.githubusercontent.com/5151242/167636279-e1e7d677-af30-4dd2-8a49-1614e1b44821.png)
5) I have done the room 1->2 transition multiple times and haven't managed to break it.
6) Pressing escape during 1->2  transition out (curtain) it crashes.
![image](https://user-images.githubusercontent.com/5151242/167636524-4df01289-e4ed-4f2d-9771-d5130479360a.png)

![image](https://user-images.githubusercontent.com/5151242/167636595-5b23a6d9-e477-49ba-a5e6-052dd94c914f.png)

The bugs from yesterday all appear fixed.

2022-05-10 18:42 UTC, BHSDuncan commented
RE the above:

1. It's actually interrupting the `exit_scene` event which is internal, but really should have no effect. As long as the behaviour that happens is ok, I'd prefer to leave this for now. Otherwise, we can look at adding `exit_scene` to the exemption list, although it's saying it's interrupting something that's queued and not running, so I'd still think it should be ok.

2. Awesome!

3. Maybe it's just the added logging, as we haven't added (or taken away) anything that's time sensitive like `wait`. The code should bear that out. There's always been a `wait` command after transitioning out and in, but that's by design. I suppose it's a matter of opinion whether it should be there (it predates my joining, though).

4. This should now be fixed.

5. Awesome!

6. This should now be fixed. In fact, we've decided to move the initiating of the pause screen to the UI. I also fixed something (pre-existing) where you could pause during the intro and the main menu (fun fact: unpausing would cause the whole UI itself to show up; whoops). We'll leave this in place until we have a way to properly skip animations/cutscenes.

2022-05-11 08:08 UTC, balloonpopper approved these changes
I can't break the latest version - all the previously reported bugs are gone as far as I can find.

2022-05-11 17:01 UTC, StraToN approved these changes

2022-05-11 17:18 UTC, merged