Fixed non-interactive objects still being interactive
godot-escoria/escoria-demo-game pull request #605
Opened 2022-07-11 21:30 UTC by dploeger

(as discussed on Discord)

2022-07-11 21:31 UTC, StraToN approved these changes

2022-07-12 10:56 UTC, balloonpopper requested changes
2 things
1) Can I please get confirmation on what this is attempting to fix so I can verify that I'm testing the right thing. It looks to be that you ignore the player or an ESCItem if is_interactive is unchecked - can someone please confirm that this is the complete scope of the fix?
2) Something looks broken, the game bogs down really badly with hundreds of "No room specified" errors when tested. (I ran the room 3 scene directly and it just bogged down immediately). I know we have PR 606 in to address these errors, but the volume of them suggests we have a much bigger problem here.

```
ESC (2022-07-12T20:52:16) D esc_room_manager.gd: Queuing room script event setup composed of 4 statements.
ESC (2022-07-12T20:52:16) D esc_event_manager.gd: Queueing event setup in channel _front.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.
ESC (2022-07-12T20:52:16) T esc_object_manager.gd: No room specified. Defaulting to current room.

```

2022-07-14 12:05 UTC, StraToN commented
@balloonpopper 
> Can I please get confirmation on what this is attempting to fix so I can verify that I'm testing the right thing. It looks to be that you ignore the player or an ESCItem if is_interactive is unchecked - can someone please confirm that this is the complete scope of the fix?

Yes, the scope is that if an item is set as non-interactive, it should not react to inputs.

> Something looks broken, the game bogs down really badly with hundreds of "No room specified" errors when tested. (I ran the room 3 scene directly and it just bogged down immediately). I know we have PR https://github.com/godot-escoria/escoria-demo-game/pull/606 in to address these errors, but the volume of them suggests we have a much bigger problem here.

I'll revert #606 locally and check again why that one happens that much. I suspect it happens in a loop.

2022-07-14 13:48 UTC, StraToN commented
Superseded by https://github.com/godot-escoria/escoria-demo-game/pull/609

2022-07-25 20:51 UTC, closed without merging