fix: Issue 181
godot-escoria/escoria-demo-game pull request #634
Opened 2022-10-20 12:54 UTC by balloonpopper

Updates some documentation along with room changes to demonstrate usage of commands without examples
Fixes https://github.com/godot-escoria/escoria-issues/issues/181

2022-10-20 16:36 UTC, BHSDuncan requested changes
Looks good! Just a few small-ish fixes.

Also, I see that there are two shader materials that are a part of this PR. Why is that?

2022-10-20 16:36 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc/commands/set_angle.gd
>  # - *degrees*: Number of degrees by which `object` is to be turned
```suggestion
# - *target_degrees*: Number of degrees by which `object` is to be turned
```

2022-10-20 16:36 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc/commands/stop_snd.gd
> +# Stops the given audio buses stream.
```suggestion
# Stops the given audio bus's stream.
```

2022-10-20 16:36 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc/commands/stop_snd.gd
> +# By default there are 3 audio busses set up by Escoria : `_sound`, which is
```suggestion
# By default there are 3 audio buses set up by Escoria : `_sound`, which is
```

2022-10-20 16:36 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc/commands/stop_snd.gd
> +# - *audio bus*: Bus to stop ("_sound", "_music", "_speech", or a custom
```suggestion
# - *audio_bus*: Bus to stop ("_sound", "_music", "_speech", or a custom
```

2022-10-20 22:33 UTC, BHSDuncan approved these changes

2022-10-24 19:41 UTC, StraToN approved these changes

2022-10-24 21:49 UTC, merged