fix: Stops error message when disabling simple dialog plugin
godot-escoria/escoria-demo-game pull request #638
Opened 2022-11-01 01:38 UTC by balloonpopper

You'll see this error if disabling the simpledialog plugin.
```
 core/project_settings.cpp:961 - Condition "!p_info.has("type")" is true.
```
For every time an empty dictionary is passed to clear a setting from Godot's project settings

```
	ESCProjectSettingsManager.register_setting(
		ESCProjectSettingsManager.MAX_TIME_TO_DISAPPEAR,
		null,
		{}
	)
```

2022-11-01 22:50 UTC, BHSDuncan requested changes
Just a couple small changes.

Please also update the doc string to show that the method can also be used to unregister/remove a project setting by sending in a `default_value` of null. Thanks!

2022-11-01 22:50 UTC, BHSDuncan commented on addons/escoria-core/game/esc_project_settings_manager.gd
> +	if ! default_value == null:
```suggestion
	if default_value != null:
```

2022-11-01 22:50 UTC, BHSDuncan commented on addons/escoria-core/game/esc_project_settings_manager.gd
> +		if ! "type" in info:
```suggestion
		if not "type" in info:
```

2022-11-02 12:40 UTC, balloonpopper commented on addons/escoria-core/game/esc_project_settings_manager.gd
> +	if ! default_value == null:
Fixed

2022-11-02 12:40 UTC, balloonpopper commented on addons/escoria-core/game/esc_project_settings_manager.gd
> +		if ! "type" in info:
Fixed

2022-11-02 13:05 UTC, balloonpopper commented
PR updated
The project_settings_manager function for creating Godot settings has been split into explicit set_setting and remove_setting functions as using set_setting to unset a setting was a code smell.
Error checking was added to the functions which then highlighted that the DEFAULT_DIALOG_TYPE was being set outside the simple_dialog plugin.

@StraToN my removal of the code that sets a default value for the setting from escoria-core/plugin.gd might cause issues with the code that is expecting to find the setting (in say.gd and esc_dialog_player.gd). If you don't have a dialog plugin active however, things aren't going to work anyway, so it seemed right to me to not be configuring the simple dialog plugin from plugin.gd. Alternatively I put it back in plugin.gd and remove it being created from simple dialog?

2022-11-02 13:44 UTC, balloonpopper commented
Damn. Realised the set_setting function needs to be able to change settings as well as create them, so the does-it-already-exist check is wrong (#showerthoughts). I'll remove it when I'm on the computer tomorrow.
The question as to whether we should set the default dialogue type from plugin.gd is still valid though.

2022-11-09 10:45 UTC, closed without merging