Fix: Wizard - verify that inventory items are written to valid folders
godot-escoria/escoria-demo-game pull request #650
Opened 2022-11-26 13:43 UTC by balloonpopper

* Added ability to change path for inventory items with a button
* Handle error when the inventory item destination folder doesn't exist
* Fixed bug where leaving the item creator with inventory item selected then going back would leave the interface with the inventory button selected, but everything else about the item interface would be for non-inventory objects.
* Minor update to a help message in the character creator

2022-11-26 21:31 UTC, BHSDuncan requested changes

2022-11-26 21:31 UTC, BHSDuncan commented on addons/escoria-wizard/item_creator.gd
> +
```suggestion
	inventory_mode = not get_node(BACKGROUND_OBJ_NODE).pressed	
```

2022-11-26 22:29 UTC, BHSDuncan approved these changes

2022-11-28 06:50 UTC, StraToN approved these changes

2022-11-28 06:50 UTC, StraToN commented on addons/escoria-wizard/CharacterCreator.tscn
> +text = "res://"
Is it normal that this settings goes away here?

2022-11-28 07:17 UTC, merged