fix: Debug message for when an item has no ESCLocation
godot-escoria/escoria-demo-game pull request #671
Opened 2023-01-17 10:04 UTC by balloonpopper

Fixes: https://github.com/godot-escoria/escoria-issues/issues/348
Also moved a few things around to put them on even coordinates for neatness.

2023-01-17 16:07 UTC, BHSDuncan approved these changes

2023-01-19 14:03 UTC, StraToN approved these changes

2023-01-19 14:04 UTC, StraToN requested changes

2023-01-19 14:04 UTC, StraToN commented on addons/escoria-core/game/core-scripts/esc_item.gd
> +			"No ESClocation found to walk to for object " +
```suggestion
			"No ESCLocation found to walk to for object " +
```

2023-01-19 14:09 UTC, StraToN approved these changes

2023-01-19 14:09 UTC, StraToN commented
Thanks a lot!

2023-01-19 14:09 UTC, merged