move dialog settings to another script to fix exported game issues
godot-escoria/escoria-demo-game pull request #678
Opened 2023-02-14 08:00 UTC by skogach

There's a problem when you try to export game and launch it, you'll get a grey screen. In the log there's errors about  `Unknown class: "EditorPlugin"` presumably because editor classes aren't exported. The problem is that `escoria-dialog-simple` plugin exports it's class name to other scripts which get settings via it. So I've moved settings to separate script that extends `Resource` same as `ESCProjectSettingsManager`. It fixes the problem.

2023-02-14 15:31 UTC, BHSDuncan commented
Thanks for this. I have a couple comments, but first, `addons/escoria-dialog-simple/esc_dialo_simple_settings.gd` has a typo in the filename (I'm sure you can see it now).

The issue you bring up is valid but also highlights something I think we overlooked: The core has an explicit reference to a class located in a plugin, which is not a good idea, e.g. what if someone wants to implement their own dialog manager?

@StraToN @balloonpopper can you see any issues or challenges in moving `ESCDialogPlayer` (and its state machine) into the Simple Dialog addon? One thing we'll need to do is make sure that `ESCProjectSettingsManager` is somehow exposed so that the Simple Dialog addon can get at things like the speech folder, speech file extension, etc.

2023-02-14 15:32 UTC, BHSDuncan requested changes
`addons/escoria-dialog-simple/esc_dialo_simple_settings.gd` has a typo in the filename. Please correct.

2023-02-14 15:32 UTC, BHSDuncan requested changes

2023-02-14 15:32 UTC, BHSDuncan commented on addons/escoria-dialog-simple/esc_dialo_simple_settings.gd
> +const SETTINGS_ROOT="escoria/dialog_simple"
```suggestion
const SETTINGS_ROOT = "escoria/dialog_simple"
```

2023-02-14 16:22 UTC, skogach commented
I fixed typo and whitespaces, also I forgot to commit changes to project file, now it's there.

2023-02-14 16:35 UTC, BHSDuncan approved these changes

2023-02-15 15:59 UTC, StraToN commented
> The issue you bring up is valid but also highlights something I think we overlooked: The core has an explicit reference to a class located in a plugin, which is not a good idea, e.g. what if someone wants to implement their own dialog manager?

We have two solutions: 
- either define a hook mechanism for any user to personalize some parts of the dialog manager. But then we'd need to define what hooks would be necessary for each needs.
- or allow a plugin to override the default behavior. Which would still require to design a clear API for this purpose.

> @StraToN @balloonpopper can you see any issues or challenges in moving ESCDialogPlayer (and its state machine) into the Simple Dialog addon? One thing we'll need to do is make sure that ESCProjectSettingsManager is somehow exposed so that the Simple Dialog addon can get at things like the speech folder, speech file extension, etc.

`ESCProjectSettingsManager` is a static class filled with static const values, so it can be used from anywhere, including a plugin.

I am a bit mixed about the idea of moving `ESCDialogPlayer` out of core. That would mean that any plugin that needs to use it will have to include it (as-is or edited for their own purpose). Again in that case I'd go in favor of some mechanism allowing one to override the default ESCDialogPlayer behavior if needed.

2023-02-15 16:06 UTC, BHSDuncan commented
Let’s discuss further on Discord when you have time. On Feb 15, 2023, at 10:59 AM, Julian Murgia ***@***.***> wrote:﻿

The issue you bring up is valid but also highlights something I think we overlooked: The core has an explicit reference to a class located in a plugin, which is not a good idea, e.g. what if someone wants to implement their own dialog manager?

We have two solutions:

either define a hook mechanism for any user to personalize some parts of the dialog manager. But then we'd need to define what hooks would be necessary for each needs.
or allow a plugin to override the default behavior. Which would still require to design a clear API for this purpose.


@StraToN @balloonpopper can you see any issues or challenges in moving ESCDialogPlayer (and its state machine) into the Simple Dialog addon? One thing we'll need to do is make sure that ESCProjectSettingsManager is somehow exposed so that the Simple Dialog addon can get at things like the speech folder, speech file extension, etc.

ESCProjectSettingsManager is a static class filled with static const values, so it can be used from anywhere, including a plugin.
I am a bit mixed about the idea of moving ESCDialogPlayer out of core. That would mean that any plugin that needs to use it will have to include it (as-is or edited for their own purpose). Again in that case I'd go in favor of some mechanism allowing one to override the default ESCDialogPlayer behavior if needed.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2023-02-15 16:11 UTC, StraToN approved these changes

2023-04-22 16:27 UTC, StraToN commented
@skogach I sincerely apologize for the time we took for reviewing and merging this PR. Thanks a lot!
Fixes https://github.com/godot-escoria/escoria-issues/issues/354
Closes https://github.com/godot-escoria/escoria-demo-game/pull/684

2023-04-22 16:27 UTC, merged