Change interaction_direction to orientation_angle
godot-escoria/escoria-demo-game pull request #702
Opened 2023-08-26 15:43 UTC by StraToN

Fixes https://github.com/godot-escoria/escoria-issues/issues/304 And some validation checks on exported parameters

2023-08-26 16:25 UTC, BHSDuncan requested changes
Looks good, but in the future let's try to avoid mixing fixes in a single commit/PR. That way we improve traceability and make things easier to find/roll back if necessary.

2023-08-26 16:25 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/behaviors/esc_movable.gd
> +			escoria.logger.warn(self, "Orientation is invalid for item %s (received value: %s)\nPath to item: %s.\nDefaulting to 0."
```suggestion
			escoria.logger.warn(self, "Orientation is invalid for item '%s' (received value: %s degrees)\nPath to item: '%s'.\nDefaulting to 0 degrees." 
```

2023-08-26 17:36 UTC, BHSDuncan approved these changes

2023-09-05 10:21 UTC, balloonpopper requested changes
I'm not sure how this is supposed to work now. I set the interaction angle for both the wrench and pipe in scene 5. Nothing seems to change regardless of the angle I've put. I've tried 0,1,2,30,45,90,8000 and the interaction is still the same each time.

2023-09-08 04:29 UTC, balloonpopper approved these changes

2023-09-08 15:35 UTC, merged