fix: use default text for dialog options if text is untranslated
godot-escoria/escoria-demo-game pull request #711
Opened 2023-10-20 20:41 UTC by enekonieto

At this moment default text is not being using in `esc_dialog_option.gd`, this PR fixes that.

I included some minor fixes also:

- fix: delete `.translation` files (`.translation` is in `.gitignore` but I think they were commited before)
- fix: delete unused translated texts (`ROOM6_dialog_1` and `ROOM6_dialog_2`)
- fix: typo in one translated text (missing tilde in `ROOM1_look_wall_item_4` spanish translation)

2023-10-20 23:14 UTC, enekonieto commented
I forgot to mention that I added a default text in the room6 dialog with the worker so the issue can be tested.

2023-10-24 11:51 UTC, StraToN approved these changes

2023-10-24 11:52 UTC, StraToN commented
Looks good to me. Waiting for other approvals. Thank you very much!

2023-10-24 15:27 UTC, BHSDuncan requested changes
I think it best to keep the updated method name close to the original intent of the referenced variable. Past that it looks ok to me.

2023-10-24 15:27 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc/types/esc_dialog_option.gd
> +var option: String setget ,get_translated_text
```suggestion
var option: String setget ,get_translated_option
```

2023-10-24 15:27 UTC, BHSDuncan commented on addons/escoria-core/game/core-scripts/esc/types/esc_dialog_option.gd
> +func get_translated_text():
```suggestion
func get_translated_option():
```

2023-10-24 15:32 UTC, enekonieto commented
> I think it best to keep the updated method name close to the original intent of the referenced variable. Past that it looks ok to me.

Done!

2023-10-24 15:33 UTC, BHSDuncan approved these changes

2023-10-28 18:31 UTC, merged